### ISSUE TITLE
This is just amazing

### ISSUE THREAD

**Issue by renjithstalin** [feram18/led-stock-ticker#10]
This is pretty amazing, I have tried various tickers using max7219/epaper etc, and this is by far the best. Thank You so very much.
setup was a breeze and it works perfectly.
Hope I'm not asking too much here, but is it possible to add another panel, with a scrolling effect just like the ones in stock exchanges?

Few observations (maybe something I have to configure, didn't dig into the settings too much)
-P10 panel displays only  a portion of the data 
-ticker name scrolling is a bit jerky

Thanks again.

**Comment by feram18** [comment]
Thank you for trying out this project!

> is it possible to add another panel, with a scrolling effect just like the ones in stock exchanges?

I'm not sure what you mean. Do you mean like a screen to scroll through some custom text? Or like scrolling through all the tickers together?

> P10 panel displays only a portion of the data

Are you able to attach a picture of this issue? It would help to get a better idea if it's an issue that should be addressed in the code, or if could be fixed on your end through some configuration.

> ticker name scrolling is a bit jerky

I've noticed some issues with scrolling myself, I am working on a fix for the next release.

**Comment by renjithstalin** [comment]
Thanks for the response, P10 panels displays like this  
![image](https://user-images.githubusercontent.com/53550078/196826726-709f14de-20cb-47a9-816e-be94380274bf.png)
![image](https://user-images.githubusercontent.com/53550078/196826755-f238092e-a547-42b7-99a9-bab01467eb68.png)
![image](https://user-images.githubusercontent.com/53550078/196826777-270e9ec8-6cf8-4307-916a-1fef47b6b459.png)

P5 panels works perfectly.
![image](https://user-images.githubusercontent.com/53550078/196826836-441a2c13-d783-4f95-b5ae-122c267a4b68.png)

_I'm not sure what you mean. Do you mean like a screen to scroll through some custom text? Or like scrolling through all the tickers together?_
I was wondering if multiple panels can be daisy-chained, to create a long one (at least with 2) to make a scrolling display, something like this : 
![image](https://user-images.githubusercontent.com/53550078/196827112-374aaf1a-ecb4-4035-aa93-586b19788c25.png)

Thanks again.

**Comment by feram18** [comment]
Added 32x16 layout support in [v0.3.1](https://github.com/feram18/led-stock-ticker/releases/tag/v0.3.1).
