### ISSUE TITLE
Percentage not updated

### ISSUE THREAD

**Issue by copyfile** [feram18/led-stock-ticker#15]
I'm running the latest version of the stock ticker now and I noticed that the percentage change is not updated. Once I do a restart of me RPI it is working again for that moment, it shows the correct percentage. I created to cronjob to restart the RPI a couple of times a day but this didn't really solve the issue, only for right after the restart. The stockprice itself is correct, so it is only limited to the percentage. Any idea what this is, and what I can/need to do to solve this?

**Comment by feram18** [comment]
Are you seeing the percentage updated at all throughout the day, or did it stay at the same value it had when it first ran?

**Comment by copyfile** [comment]
Have tested it a couple of days now but it looks to be okay now. Thanks!
