### ISSUE TITLE
Not showing anything besides the clock

### ISSUE THREAD

**Issue by PHI34Halladay** [feram18/led-stock-ticker#19]
Hi guys,

I only get to see the date and time right now.

This is the error from the log file:

![image](https://user-images.githubusercontent.com/46962608/226658099-d65c5c6c-8795-485f-aec1-8014f6c42ef3.png)

What am I doing wrong and how can I fix it?

Thanks in advance

**Comment by feram18** [comment]
These messages should only come up if yahoo finance wasn't able to resolve the ticker, but clearly these are all valid options.
Though occasionally on testing I've seen this error come up on valid tickers, I just attributed it to network errors. 

Is your Pi able to connect to other online services? Did you try it multiple times with the same results?

Try also adding the `--debug` flag on your execution command, it should give us more detailed logs to get a better idea of what's causing the issue.

**Comment by PHI34Halladay** [comment]
I can connect to the internet on the pi, so this should not be the problem.

I tried it multiple times on multiple days.

Here's the complete log file
[led-stock-ticker.log](https://github.com/feram18/led-stock-ticker/files/11059963/led-stock-ticker.log)

**Comment by feram18** [comment]
It's odd, I don't see any exceptions being thrown at all. It seems as if the responses are coming back empty from the api.
What's your setup like? (Pi model, OS & Python version, etc).

I would try reinstalling the dependencies `sudo pip3 install -r requirements.txt` in case it's an issue with a `yahooquery` version.

**Comment by PHI34Halladay** [comment]
I'm on a Raspberry 4 Model B and I have Python 2.7.16 installed.

Also did a complete reinstall of the dependencies without any difference.

**Comment by feram18** [comment]
I think the Python version might be the issue. I am using some Python 3.7 features in this project.
