### ISSUE TITLE
Led offset at the bottom of the stock curve

### ISSUE THREAD

**Issue by Gautchh** [feram18/led-stock-ticker#22]
**Led offset at the bottom of the stock curve**
When some curve stock is show on the RGB matrix, there is some missing led at the bottom. If I understand how it works, the curve should always touch the bottom at least once and on like 50% of the curve stock the curve didn't touch the bottom.

**Configuration**
 - Raspberry Pi 3B+
 - Operative System: Raspberry Pi OS
 - LED Matrix Size: 128×64
 - Display Adapter: Adafruit RGB Matrix HAT
 - Led stock ticker v0.3.10

**Screenshots/Logs**
![PXL_20230407_133720857](https://user-images.githubusercontent.com/39910545/231473371-889acda2-5359-45a3-898f-3e96c10b6771.jpg)
![PXL_20230407_133740368](https://user-images.githubusercontent.com/39910545/231473436-572a4036-d2d6-4d05-84b9-ad1d324fbe07.jpg)
![PXL_20230407_133749503](https://user-images.githubusercontent.com/39910545/231473467-594dab4a-ecea-40c6-a1df-18e0cf838574.jpg)
![PXL_20230407_133820247](https://user-images.githubusercontent.com/39910545/231473532-26454b75-e17c-4232-9922-5d6be52b41a0.jpg)
On all this picture the curve stock doesn't touch the bottom and I don't know why.

Thank you for your project, I hope your project will be more used !
Have a great day.

**Comment by feram18** [comment]
Fixed in [v0.3.15](https://github.com/feram18/led-stock-ticker/releases/tag/v0.3.15).
