### ISSUE TITLE
Can someone please provide a link to a compatible 128x64 display?

### ISSUE THREAD

**Issue by Jord4n** [feram18/led-stock-ticker#29]
Or does one just need to use 2x 64x64?

**Comment by feram18** [comment]
I purchased my 128x64 board from AliExpress [here](https://www.aliexpress.us/item/3256802066388935.html). But there are quite a few other cheaper listings if you search for "RGB LED Matrix 128x64" on there.

You can also do two 64x64, but would probably be pricier to buy two separate boards. It's cleaner to go with a single 128x64 board.
