### ISSUE TITLE
How do I attach the 128x64 dual board with two ribbons to the pi?

### ISSUE THREAD

**Issue by Jord4n** [feram18/led-stock-ticker#37]
I see hats with only 1 ribbon connector port and another with 3 connectors but no external power.  A bit confused. as this 128x64 LED board I have has two connector ribbons.  How can I connect it?

Thanks for any help!

**Comment by feram18** [comment]
By dual board, do you mean you have two 64x64 boards? or two 128x64?

Each board should have two ribbon connectors at the back, you can daisy chain the boards using the ribbon cable. 
One of the boards will be connected to the Pi hat, this board will have a power connector and will share power to the second board. The second board which is only connected to the first board does not need to be connected to the hat. Kind of [like this](https://there.oughta.be/assets/resized/images/2020-09-28/1280/daisychain.jpg).

**Comment by Jord4n** [comment]
Ah!  I see!  Thank you so much, I missed that bit!  Thank you!
