### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by Zobrob** [feram18/led-stock-ticker#7]
Hey thanks a lot for this awesome project and the nice documentation.
Even indices work 👍 
If you should ever consider an alternative design, I would love to have the logos for Bitcoin and Ethereum (instead of the history).
Another nice feature would be daily winners and losers of certain categories (e.g. a stock index, or top100 crypto).

**Comment by feram18** [comment]
Thanks for the feedback, suggestions are always welcome!

I am working on some new features, slowly due to lack of time, but coming along. Adding logos in place of history chart is actually one of the things on the to-do list. I'll keep the daily winners/losers in mind for a future update.

**Comment by Zobrob** [comment]
That's great to hear, thank you.

**Comment by feram18** [comment]
Thank you for the feedback! I'll update the README to mark the HAT/Bonnet as recommended but optional components. Thanks for the support!
