### ISSUE TITLE
Unable to install and start

### ISSUE THREAD

**Issue by copyfile** [feram18/led-stock-ticker#8]
I have a completely fresh install of raspberry PI OS and then followed all the commands to install the stock ticker. But for some reason it is not starting/showing anything on the led matrix. I tried a test script from adafruit and that works, so the connection and led matrix are working. Is there something I'm doing wrong? See below all the commands and results (I also have the easier to read Word file on Wetransfer https://we.tl/t-4w0f4ofdq2 ):

`pi@raspberrypi:~ $ sudo apt-get update
Hit:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease
Reading package lists... Done             
pi@raspberrypi:~ $ sudo apt-get install git python-pip
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python-pip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python3-pip

E: Package 'python-pip' has no installation candidate
pi@raspberrypi:~ $ git clone --recursive https://github.com/feram18/led-stock-ticker.git
Cloning into 'led-stock-ticker'...
remote: Enumerating objects: 1075, done.
remote: Counting objects: 100% (85/85), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 1075 (delta 54), reused 53 (delta 40), pack-reused 990
Receiving objects: 100% (1075/1075), 44.82 MiB | 4.88 MiB/s, done.
Resolving deltas: 100% (685/685), done.
Submodule 'rpi-rgb-led-matrix' (https://github.com/hzeller/rpi-rgb-led-matrix.git) registered for path 'rpi-rgb-led-matrix'
Cloning into '/home/pi/led-stock-ticker/rpi-rgb-led-matrix'...
remote: Enumerating objects: 4892, done.        
remote: Total 4892 (delta 0), reused 0 (delta 0), pack-reused 4892        
Receiving objects: 100% (4892/4892), 22.24 MiB | 5.58 MiB/s, done.
Resolving deltas: 100% (3383/3383), done.
Submodule path 'rpi-rgb-led-matrix': checked out 'a56338db0f003d5236f2ce98c73a591d64a70852'
pi@raspberrypi:~ $ cd led-stock-ticker
pi@raspberrypi:~/led-stock-ticker $ chmod +x install.sh
pi@raspberrypi:~/led-stock-ticker $ ./install.sh
___________________________________________________________________
   __   _______    ______           __     _______     __          
  / /  / __/ _ \  / __/ /____  ____/ /__  /_  __(_)___/ /_____ ____
 / /__/ _// // / _\ \/ __/ _ \/ __/  '_/   / / / / __/  '_/ -_) __/
/____/___/____/ /___/\__/\___/\__/_/\_\   /_/ /_/\__/_/\_\__/_/   
___________________________________________________________________

Updating system & installing Python 3
Hit:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-dev is already the newest version (3.9.2-3).
The following package was automatically installed and is no longer required:
  libfuse2
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 51 not upgraded.

Installing rpi-rgb-led-matrix library...
make -C ./lib
make[1]: Entering directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o gpio.o gpio.cc
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o led-matrix.o led-matrix.cc
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o options-initialize.o options-initialize.cc
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o framebuffer.o framebuffer.cc
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o thread.o thread.cc
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o bdf-font.o bdf-font.cc
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o graphics.o graphics.cc
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o led-matrix-c.o led-matrix-c.cc
cc  -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -c -o hardware-mapping.o hardware-mapping.c
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o pixel-mapper.o pixel-mapper.cc
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o multiplex-mappers.o multiplex-mappers.cc
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o content-streamer.o content-streamer.cc
ar rcs librgbmatrix.a gpio.o led-matrix.o options-initialize.o framebuffer.o thread.o bdf-font.o graphics.o led-matrix-c.o hardware-mapping.o pixel-mapper.o multiplex-mappers.o content-streamer.o
g++ -shared -Wl,-soname,librgbmatrix.so.1 -o librgbmatrix.so.1 gpio.o led-matrix.o options-initialize.o framebuffer.o thread.o bdf-font.o graphics.o led-matrix-c.o hardware-mapping.o pixel-mapper.o multiplex-mappers.o content-streamer.o -lpthread  -lrt -lm -lpthread
make[1]: Leaving directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
make -C examples-api-use
make[1]: Entering directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/examples-api-use'
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o demo-main.o demo-main.cc
make -C ../lib
make[2]: Entering directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
make[2]: Leaving directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
g++ demo-main.o -o demo -L../lib -lrgbmatrix -lrt -lm -lpthread
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o minimal-example.o minimal-example.cc
g++ minimal-example.o -o minimal-example -L../lib -lrgbmatrix -lrt -lm -lpthread
cc -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o c-example.o c-example.c
cc c-example.o -o c-example -L../lib -lrgbmatrix -lrt -lm -lpthread -lstdc++
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o text-example.o text-example.cc
g++ text-example.o -o text-example -L../lib -lrgbmatrix -lrt -lm -lpthread
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o scrolling-text-example.o scrolling-text-example.cc
g++ scrolling-text-example.o -o scrolling-text-example -L../lib -lrgbmatrix -lrt -lm -lpthread
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o clock.o clock.cc
g++ clock.o -o clock -L../lib -lrgbmatrix -lrt -lm -lpthread
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o ledcat.o ledcat.cc
g++ ledcat.o -o ledcat -L../lib -lrgbmatrix -lrt -lm -lpthread
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o input-example.o input-example.cc
g++ input-example.o -o input-example -L../lib -lrgbmatrix -lrt -lm -lpthread
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o pixel-mover.o pixel-mover.cc
g++ pixel-mover.o -o pixel-mover -L../lib -lrgbmatrix -lrt -lm -lpthread
make[1]: Leaving directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/examples-api-use'
make -C bindings/python build
make[1]: Entering directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/bindings/python'
make -C ../../lib
make[2]: Entering directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
make[2]: Leaving directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
/usr/bin/python3 setup.py build --build-lib .
running build
running build_py
running build_ext
building 'core' extension
creating build
creating build/temp.linux-armv7l-3.9
creating build/temp.linux-armv7l-3.9/rgbmatrix
arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I../../include -I/usr/include/python3.9 -c rgbmatrix/core.cpp -o build/temp.linux-armv7l-3.9/rgbmatrix/core.o -O3 -Wall
arm-linux-gnueabihf-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-armv7l-3.9/rgbmatrix/core.o -L../../lib -lrgbmatrix -o ./rgbmatrix/core.cpython-39-arm-linux-gnueabihf.so
building 'graphics' extension
arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I../../include -I/usr/include/python3.9 -c rgbmatrix/graphics.cpp -o build/temp.linux-armv7l-3.9/rgbmatrix/graphics.o -O3 -Wall
arm-linux-gnueabihf-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-armv7l-3.9/rgbmatrix/graphics.o -L../../lib -lrgbmatrix -o ./rgbmatrix/graphics.cpython-39-arm-linux-gnueabihf.so
make[1]: Leaving directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/bindings/python'
make -C ./lib
make[1]: Entering directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
make[1]: Leaving directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
make -C examples-api-use
make[1]: Entering directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/examples-api-use'
make -C ../lib
make[2]: Entering directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
make[2]: Leaving directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
make[1]: Leaving directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/examples-api-use'
make -C bindings/python build
make[1]: Entering directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/bindings/python'
make -C ../../lib
make[2]: Entering directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
make[2]: Leaving directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
/usr/bin/python3 setup.py build --build-lib .
running build
running build_py
running build_ext
make[1]: Leaving directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/bindings/python'
make -C bindings/python install
make[1]: Entering directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/bindings/python'
/usr/bin/python3 setup.py install
running install
running build
running build_py
creating build/lib.linux-armv7l-3.9
creating build/lib.linux-armv7l-3.9/rgbmatrix
copying rgbmatrix/__init__.py -> build/lib.linux-armv7l-3.9/rgbmatrix
running build_ext
building 'core' extension
arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I../../include -I/usr/include/python3.9 -c rgbmatrix/core.cpp -o build/temp.linux-armv7l-3.9/rgbmatrix/core.o -O3 -Wall
arm-linux-gnueabihf-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-armv7l-3.9/rgbmatrix/core.o -L../../lib -lrgbmatrix -o build/lib.linux-armv7l-3.9/rgbmatrix/core.cpython-39-arm-linux-gnueabihf.so
building 'graphics' extension
arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I../../include -I/usr/include/python3.9 -c rgbmatrix/graphics.cpp -o build/temp.linux-armv7l-3.9/rgbmatrix/graphics.o -O3 -Wall
arm-linux-gnueabihf-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-armv7l-3.9/rgbmatrix/graphics.o -L../../lib -lrgbmatrix -o build/lib.linux-armv7l-3.9/rgbmatrix/graphics.cpython-39-arm-linux-gnueabihf.so
running install_lib
copying build/lib.linux-armv7l-3.9/rgbmatrix/graphics.cpython-39-arm-linux-gnueabihf.so -> /usr/local/lib/python3.9/dist-packages/rgbmatrix
copying build/lib.linux-armv7l-3.9/rgbmatrix/__init__.py -> /usr/local/lib/python3.9/dist-packages/rgbmatrix
copying build/lib.linux-armv7l-3.9/rgbmatrix/core.cpython-39-arm-linux-gnueabihf.so -> /usr/local/lib/python3.9/dist-packages/rgbmatrix
byte-compiling /usr/local/lib/python3.9/dist-packages/rgbmatrix/__init__.py to __init__.cpython-39.pyc
running install_egg_info
Removing /usr/local/lib/python3.9/dist-packages/rgbmatrix-0.0.1.egg-info
Writing /usr/local/lib/python3.9/dist-packages/rgbmatrix-0.0.1.egg-info
make[1]: Leaving directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/bindings/python'
Updating repository...
HEAD is now at 958354a build(rpi-rgb-led-matrix): add --led-inverse flag
M	rpi-rgb-led-matrix
Note: switching to 'tags/v0.2.3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 1bdc8b5 build: v0.2.3

Installing dependencies...
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: lxml>=4.5.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (4.6.3)
Requirement already satisfied: numpy>=1.16.6 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (1.19.5)
Requirement already satisfied: multitasking~=0.0.9 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 3)) (0.0.11)
Requirement already satisfied: pandas>=0.23.1 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 4)) (1.4.3)
Requirement already satisfied: pillow>=8.2.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 5)) (9.2.0)
Requirement already satisfied: pytz>=2021.1 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 6)) (2022.2.1)
Requirement already satisfied: questionary>=1.10.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 7)) (1.10.0)
Requirement already satisfied: requests>=2.22.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 8)) (2.28.1)
Requirement already satisfied: wheel>=0.37.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 9)) (0.37.1)
Requirement already satisfied: yfinance>=0.1.63 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 10)) (0.1.74)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=0.23.1->-r requirements.txt (line 4)) (2.8.2)
Requirement already satisfied: prompt_toolkit<4.0,>=2.0 in /usr/local/lib/python3.9/dist-packages (from questionary>=1.10.0->-r requirements.txt (line 7)) (3.0.31)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.22.0->-r requirements.txt (line 8)) (2020.6.20)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.9/dist-packages (from requests>=2.22.0->-r requirements.txt (line 8)) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests>=2.22.0->-r requirements.txt (line 8)) (1.26.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.22.0->-r requirements.txt (line 8)) (2.10)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.9/dist-packages (from prompt_toolkit<4.0,>=2.0->questionary>=1.10.0->-r requirements.txt (line 7)) (0.2.5)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.1->pandas>=0.23.1->-r requirements.txt (line 4)) (1.16.0)
Creating new config.json file...
Set your preferences using the command ./config.py
Update completed

If there are no errors shown above, installation was successful.
To make sure your matrix is working properly, execute the samples located in ./rpi-rgb-led-matrix/bindings/python/samples
pi@raspberrypi:~/led-stock-ticker $ ./update.sh
Updating repository...
HEAD is now at 1bdc8b5 build: v0.2.3
M	rpi-rgb-led-matrix
HEAD is now at 1bdc8b5 build: v0.2.3

Installing dependencies...
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: lxml>=4.5.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (4.6.3)
Requirement already satisfied: numpy>=1.16.6 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (1.19.5)
Requirement already satisfied: multitasking~=0.0.9 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 3)) (0.0.11)
Requirement already satisfied: pandas>=0.23.1 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 4)) (1.4.3)
Requirement already satisfied: pillow>=8.2.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 5)) (9.2.0)
Requirement already satisfied: pytz>=2021.1 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 6)) (2022.2.1)
Requirement already satisfied: questionary>=1.10.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 7)) (1.10.0)
Requirement already satisfied: requests>=2.22.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 8)) (2.28.1)
Requirement already satisfied: wheel>=0.37.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 9)) (0.37.1)
Requirement already satisfied: yfinance>=0.1.63 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 10)) (0.1.74)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=0.23.1->-r requirements.txt (line 4)) (2.8.2)
Requirement already satisfied: prompt_toolkit<4.0,>=2.0 in /usr/local/lib/python3.9/dist-packages (from questionary>=1.10.0->-r requirements.txt (line 7)) (3.0.31)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.22.0->-r requirements.txt (line 8)) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests>=2.22.0->-r requirements.txt (line 8)) (1.26.5)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.9/dist-packages (from requests>=2.22.0->-r requirements.txt (line 8)) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.22.0->-r requirements.txt (line 8)) (2020.6.20)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.9/dist-packages (from prompt_toolkit<4.0,>=2.0->questionary>=1.10.0->-r requirements.txt (line 7)) (0.2.5)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.1->pandas>=0.23.1->-r requirements.txt (line 4)) (1.16.0)
Update completed
pi@raspberrypi:~/led-stock-ticker $ ./config.py
Traceback (most recent call last):
  File "/home/pi/led-stock-ticker/./config.py", line 10, in <module>
    from util.utils import read_json, write_json
  File "/home/pi/led-stock-ticker/util/utils.py", line 18, in <module>
    from util.holiday_calendar import MarketHolidayCalendar
  File "/home/pi/led-stock-ticker/util/holiday_calendar.py", line 1, in <module>
    from pandas.tseries.offsets import WeekOfMonth
  File "/usr/local/lib/python3.9/dist-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "/usr/local/lib/python3.9/dist-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/usr/local/lib/python3.9/dist-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/usr/local/lib/python3.9/dist-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/usr/local/lib/python3.9/dist-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa:F401
  File "/usr/local/lib/python3.9/dist-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 48 from C header, got 40 from PyObject
pi@raspberrypi:~/led-stock-ticker $ sudo python3 main.py --led-gpio-mapping="adafruit-hat" --led-slowdown-gpio=2
Traceback (most recent call last):
  File "/home/pi/led-stock-ticker/main.py", line 6, in <module>
    from util.utils import args, led_matrix_options
  File "/home/pi/led-stock-ticker/util/utils.py", line 18, in <module>
    from util.holiday_calendar import MarketHolidayCalendar
  File "/home/pi/led-stock-ticker/util/holiday_calendar.py", line 1, in <module>
    from pandas.tseries.offsets import WeekOfMonth
  File "/usr/local/lib/python3.9/dist-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "/usr/local/lib/python3.9/dist-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/usr/local/lib/python3.9/dist-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/usr/local/lib/python3.9/dist-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/usr/local/lib/python3.9/dist-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa:F401
  File "/usr/local/lib/python3.9/dist-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 48 from C header, got 40 from PyObject

`

**Comment by feram18** [comment]
> Package python-pip is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> However the following packages replace it:
> python3-pip
> 
> E: Package 'python-pip' has no installation candidate

I'll be updating the README to account for this mistake. Try `sudo apt-get install python3-pip -y` instead. Then try re-running the `update.sh` script.

---

> ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 48 from C header, got 40 from PyObject

This error appears to be related to the numpy dependency only, try reinstalling with:

`pip3 install --upgrade numpy`

**Comment by copyfile** [comment]
Thanks for your reply! I have run both changes but unfortunatly it is not (yet) working. See below what's happening when trying to perform these actions:

pi@raspberrypi:~ $ sudo apt-get install python3-pip -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pip is already the newest version (20.3.4-4+rpt1+deb11u1).
The following package was automatically installed and is no longer required:
  libfuse2
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 23 not upgraded.


pi@raspberrypi:~/led-stock-ticker $ pip3 install --upgrade numpy
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (1.23.3)
Collecting numpy
  Downloading https://www.piwheels.org/simple/numpy/numpy-1.23.3-cp39-cp39-linux_armv7l.whl (12.4 MB)
     |████████████████████████████████| 12.4 MB 72 kB/s 
  Downloading https://www.piwheels.org/simple/numpy/numpy-1.23.2-cp39-cp39-linux_armv7l.whl (12.3 MB)
     |████████████████████████████████| 12.3 MB 75 kB/s 


pi@raspberrypi:~/led-stock-ticker $ ./config.py
Traceback (most recent call last):
  File "/home/pi/led-stock-ticker/./config.py", line 10, in <module>
    from util.utils import read_json, write_json
  File "/home/pi/led-stock-ticker/util/utils.py", line 18, in <module>
    from util.holiday_calendar import MarketHolidayCalendar
  File "/home/pi/led-stock-ticker/util/holiday_calendar.py", line 1, in <module>
    from pandas.tseries.offsets import WeekOfMonth
  File "/usr/local/lib/python3.9/dist-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/usr/bin/python3"
  * The NumPy version is: "1.23.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libcblas.so.3: cannot open shared object file: No such file or directory

pi@raspberrypi:~/led-stock-ticker $ sudo python3 main.py --led-gpio-mapping="adafruit-hat" --led-slowdown-gpio=2
Traceback (most recent call last):
  File "/home/pi/led-stock-ticker/main.py", line 6, in <module>
    from util.utils import args, led_matrix_options
  File "/home/pi/led-stock-ticker/util/utils.py", line 18, in <module>
    from util.holiday_calendar import MarketHolidayCalendar
  File "/home/pi/led-stock-ticker/util/holiday_calendar.py", line 1, in <module>
    from pandas.tseries.offsets import WeekOfMonth
  File "/usr/local/lib/python3.9/dist-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/usr/bin/python3"
  * The NumPy version is: "1.23.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libcblas.so.3: cannot open shared object file: No such file or directory

pi@raspberrypi:~/led-stock-ticker $

**Comment by copyfile** [comment]
I was able to get it working now with installing a legacy version of Rasbarian! Thanks!!
