### ISSUE TITLE
Not really issue more question 

### ISSUE THREAD

**Issue by Batman6576** [feram18/led-stock-ticker#9]
Would I be able to change the api too sports and have it like a sports ticker. Sorry new to coding trying to hook up a 32 by 128 ticket.

**Comment by feram18** [comment]
Unfortunately no, there's a lot more going on behind the scenes so it would take quite a bit of work to repurpose this specific project into a sports one, though the overall logic would still be pretty similar.

There are already some sports boards out there. I personally use these:

- MLB: https://github.com/MLB-LED-Scoreboard/mlb-led-scoreboard
- NHL: https://github.com/riffnshred/nhl-led-scoreboard

There also seems to be an NFL one in the works (https://github.com/mikemountain/nfl-led-scoreboard), which I personally have not yet tried out.

I am also currently working through a Formula 1 board as well: https://github.com/feram18/f1-led-leaderboard
